import {
  Award,
  Baby,
  Banknote,
  BarChart,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Clock,
  Coffee,
  CornerUpLeft,
  Cpu,
  CreditCard,
  Dice1,
  DollarSign,
  Droplet,
  Eye,
  FileText,
  FireExtinguisher,
  Gift,
  Globe2,
  Handshake,
  Heart,
  Home,
  LifeBuoy,
  MapPin,
  MoreHorizontal,
  Music,
  PawPrint,
  Percent,
  Phone,
  PieChart,
  Pill,
  Plane,
  Repeat,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Thermometer,
  TrendingUp,
  Tv,
  User,
  UserMinus,
  UserPlus,
  Users,
  Wallet,
  Wrench,
  Zap,
} from "lucide-react";

export const TransactionCategories = [
  { id: 1, name: "Salary", type: "income", icon: DollarSign },
  { id: 2, name: "Bonus", type: "income", icon: Gift },
  { id: 3, name: "Commission", type: "income", icon: Percent },
  { id: 4, name: "Freelance", type: "income", icon: Briefcase },
  { id: 5, name: "Rental Income", type: "income", icon: Home },
  { id: 6, name: "Interest Income", type: "income", icon: TrendingUp },
  { id: 7, name: "Dividend Income", type: "income", icon: PieChart },
  { id: 8, name: "Capital Gains", type: "income", icon: BarChart },
  { id: 9, name: "Investment Income", type: "income", icon: Wallet },
  { id: 10, name: "Pension", type: "income", icon: Clock },
  { id: 11, name: "Social Security", type: "income", icon: Users },
  { id: 12, name: "Disability Benefits", type: "income", icon: Shield },
  { id: 13, name: "Unemployment Benefits", type: "income", icon: UserMinus },
  { id: 14, name: "Child Support", type: "income", icon: UserPlus },
  { id: 15, name: "Alimony", type: "income", icon: Handshake },
  { id: 16, name: "Gift Income", type: "income", icon: Gift },
  { id: 17, name: "Refunds", type: "income", icon: CornerUpLeft },
  { id: 18, name: "Royalties", type: "income", icon: Award },
  { id: 19, name: "Scholarships & Grants", type: "income", icon: BookOpen },
  { id: 20, name: "Lottery & Gambling", type: "income", icon: Dice1 },

  { id: 21, name: "Rent / Mortgage", type: "expense", icon: Home },
  { id: 22, name: "Property Tax", type: "expense", icon: FileText },
  { id: 23, name: "Home Insurance", type: "expense", icon: ShieldCheck },
  { id: 24, name: "HOA Fees", type: "expense", icon: Users },
  {
    id: 25,
    name: "Home Maintenance & Repairs",
    type: "expense",
    icon: Wrench,
  },
  { id: 26, name: "Utilities - Electricity", type: "expense", icon: Zap },
  { id: 27, name: "Utilities - Water", type: "expense", icon: Droplet },
  {
    id: 28,
    name: "Utilities - Gas",
    type: "expense",
    icon: FireExtinguisher,
  },
  { id: 29, name: "Heating / Fuel Oil", type: "expense", icon: Thermometer },
  { id: 30, name: "Internet", type: "expense", icon: Globe2 },
  { id: 31, name: "Phone", type: "expense", icon: Phone },
  { id: 32, name: "Cable / Streaming", type: "expense", icon: Tv },
  { id: 33, name: "Groceries", type: "expense", icon: ShoppingCart },
  { id: 34, name: "Dining Out", type: "expense", icon: Coffee },
  { id: 35, name: "Coffee & Snacks", type: "expense", icon: Coffee },
  { id: 36, name: "Transportation - Fuel", type: "expense", icon: Car },
  {
    id: 37,
    name: "Transportation - Public Transit",
    type: "expense",
    icon: Bus,
  },
  { id: 38, name: "Car Payment", type: "expense", icon: CreditCard },
  { id: 39, name: "Car Insurance", type: "expense", icon: ShieldCheck },
  {
    id: 40,
    name: "Car Maintenance & Repairs",
    type: "expense",
    icon: Wrench,
  },
  { id: 41, name: "Parking & Tolls", type: "expense", icon: MapPin },
  { id: 42, name: "Health Insurance", type: "expense", icon: Shield },
  { id: 43, name: "Medical Expenses", type: "expense", icon: Heart },
  { id: 44, name: "Dental", type: "expense", icon: Smile },
  { id: 45, name: "Pharmacy", type: "expense", icon: Pill },
  { id: 46, name: "Vision Care", type: "expense", icon: Eye },
  { id: 47, name: "Childcare", type: "expense", icon: Baby },
  { id: 48, name: "Education / Tuition", type: "expense", icon: BookOpen },
  { id: 49, name: "Student Loan Payment", type: "expense", icon: CreditCard },
  { id: 50, name: "Life Insurance", type: "expense", icon: LifeBuoy },
  { id: 51, name: "Pet Care", type: "expense", icon: PawPrint },
  { id: 52, name: "Clothing & Apparel", type: "expense", icon: ShoppingBag },
  { id: 53, name: "Personal Care", type: "expense", icon: User },
  {
    id: 54,
    name: "Subscriptions & Memberships",
    type: "expense",
    icon: Repeat,
  },
  { id: 55, name: "Entertainment", type: "expense", icon: Music },
  { id: 56, name: "Travel & Vacation", type: "expense", icon: Plane },
  { id: 57, name: "Gifts & Donations", type: "expense", icon: Gift },
  { id: 58, name: "Taxes - Income", type: "expense", icon: FileText },
  { id: 59, name: "Taxes - Other", type: "expense", icon: FileText },
  { id: 60, name: "Banking & Fees", type: "expense", icon: Banknote },
  { id: 61, name: "Business Expenses", type: "expense", icon: Briefcase },
  { id: 62, name: "Office Supplies", type: "expense", icon: FileText },
  { id: 63, name: "Software & Apps", type: "expense", icon: Cpu },
  {
    id: 64,
    name: "Investments - Contributions",
    type: "expense",
    icon: Wallet,
  },
  { id: 65, name: "Miscellaneous", type: "expense", icon: MoreHorizontal },
] as const;

export type TransactionCategory =
  (typeof TransactionCategories)[number]["name"];
