import {
  Award,
  Baby,
  Banknote,
  BarChart,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Clock,
  Coffee,
  CornerUpLeft,
  Cpu,
  CreditCard,
  Dice1,
  DollarSign,
  Droplet,
  Eye,
  FileText,
  FireExtinguisher,
  Gift,
  Globe2,
  Handshake,
  Heart,
  Home,
  LifeBuoy,
  MapPin,
  MoreHorizontal,
  Music,
  PawPrint,
  Percent,
  Phone,
  PieChart,
  Pill,
  Plane,
  Repeat,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Thermometer,
  TrendingUp,
  Tv,
  User,
  UserMinus,
  UserPlus,
  Users,
  Wallet,
  Wrench,
  Zap,
} from "lucide-react";

export const TransactionCategories = [
  {
    id: 1,
    name: "Salary",
    type: "income",
    icon: DollarSign,
    color: "from-orange-200 to-orange-300",
  },
  {
    id: 2,
    name: "Bonus",
    type: "income",
    icon: Gift,
    color: "from-orange-300 to-orange-400",
  },
  {
    id: 3,
    name: "Commission",
    type: "income",
    icon: Percent,
    color: "from-orange-400 to-orange-500",
  },
  {
    id: 4,
    name: "Freelance",
    type: "income",
    icon: Briefcase,
    color: "from-orange-500 to-orange-600",
  },
  {
    id: 5,
    name: "Rental Income",
    type: "income",
    icon: Home,
    color: "from-orange-600 to-orange-700",
  },
  {
    id: 6,
    name: "Interest Income",
    type: "income",
    icon: TrendingUp,
    color: "from-amber-200 to-amber-300",
  },
  {
    id: 7,
    name: "Dividend Income",
    type: "income",
    icon: PieChart,
    color: "from-amber-300 to-amber-400",
  },
  {
    id: 8,
    name: "Capital Gains",
    type: "income",
    icon: BarChart,
    color: "from-amber-400 to-amber-500",
  },
  {
    id: 9,
    name: "Investment Income",
    type: "income",
    icon: Wallet,
    color: "from-amber-500 to-amber-600",
  },
  {
    id: 10,
    name: "Pension",
    type: "income",
    icon: Clock,
    color: "from-amber-600 to-amber-700",
  },
  {
    id: 11,
    name: "Social Security",
    type: "income",
    icon: Users,
    color: "from-yellow-200 to-yellow-300",
  },
  {
    id: 12,
    name: "Disability Benefits",
    type: "income",
    icon: Shield,
    color: "from-yellow-300 to-yellow-400",
  },
  {
    id: 13,
    name: "Unemployment Benefits",
    type: "income",
    icon: UserMinus,
    color: "from-yellow-400 to-yellow-500",
  },
  {
    id: 14,
    name: "Child Support",
    type: "income",
    icon: UserPlus,
    color: "from-yellow-500 to-yellow-600",
  },
  {
    id: 15,
    name: "Alimony",
    type: "income",
    icon: Handshake,
    color: "from-yellow-600 to-yellow-700",
  },
  {
    id: 16,
    name: "Gift Income",
    type: "income",
    icon: Gift,
    color: "from-lime-200 to-lime-300",
  },
  {
    id: 17,
    name: "Refunds",
    type: "income",
    icon: CornerUpLeft,
    color: "from-lime-300 to-lime-400",
  },
  {
    id: 18,
    name: "Royalties",
    type: "income",
    icon: Award,
    color: "from-lime-400 to-lime-500",
  },
  {
    id: 19,
    name: "Scholarships & Grants",
    type: "income",
    icon: BookOpen,
    color: "from-lime-500 to-lime-600",
  },
  {
    id: 20,
    name: "Lottery & Gambling",
    type: "income",
    icon: Dice1,
    color: "from-lime-600 to-lime-700",
  },

  {
    id: 21,
    name: "Rent / Mortgage",
    type: "expense",
    icon: Home,
    color: "from-green-200 to-green-300",
  },
  {
    id: 22,
    name: "Property Tax",
    type: "expense",
    icon: FileText,
    color: "from-green-300 to-green-400",
  },
  {
    id: 23,
    name: "Home Insurance",
    type: "expense",
    icon: ShieldCheck,
    color: "from-green-400 to-green-500",
  },
  {
    id: 24,
    name: "HOA Fees",
    type: "expense",
    icon: Users,
    color: "from-green-500 to-green-600",
  },
  {
    id: 25,
    name: "Home Maintenance & Repairs",
    type: "expense",
    icon: Wrench,
    color: "from-green-600 to-green-700",
  },
  {
    id: 26,
    name: "Utilities - Electricity",
    type: "expense",
    icon: Zap,
    color: "from-emerald-200 to-emerald-300",
  },
  {
    id: 27,
    name: "Utilities - Water",
    type: "expense",
    icon: Droplet,
    color: "from-emerald-300 to-emerald-400",
  },
  {
    id: 28,
    name: "Utilities - Gas",
    type: "expense",
    icon: FireExtinguisher,
    color: "from-emerald-400 to-emerald-500",
  },
  {
    id: 29,
    name: "Heating / Fuel Oil",
    type: "expense",
    icon: Thermometer,
    color: "from-emerald-500 to-emerald-600",
  },
  {
    id: 30,
    name: "Internet",
    type: "expense",
    icon: Globe2,
    color: "from-emerald-600 to-emerald-700",
  },
  {
    id: 31,
    name: "Phone",
    type: "expense",
    icon: Phone,
    color: "from-teal-200 to-teal-300",
  },
  {
    id: 32,
    name: "Cable / Streaming",
    type: "expense",
    icon: Tv,
    color: "from-teal-300 to-teal-400",
  },
  {
    id: 33,
    name: "Groceries",
    type: "expense",
    icon: ShoppingCart,
    color: "from-teal-400 to-teal-500",
  },
  {
    id: 34,
    name: "Dining Out",
    type: "expense",
    icon: Coffee,
    color: "from-teal-500 to-teal-600",
  },
  {
    id: 35,
    name: "Coffee & Snacks",
    type: "expense",
    icon: Coffee,
    color: "from-teal-600 to-teal-700",
  },
  {
    id: 36,
    name: "Transportation - Fuel",
    type: "expense",
    icon: Car,
    color: "from-cyan-200 to-cyan-300",
  },
  {
    id: 37,
    name: "Transportation - Public Transit",
    type: "expense",
    icon: Bus,
    color: "from-cyan-300 to-cyan-400",
  },
  {
    id: 38,
    name: "Car Payment",
    type: "expense",
    icon: CreditCard,
    color: "from-cyan-400 to-cyan-500",
  },
  {
    id: 39,
    name: "Car Insurance",
    type: "expense",
    icon: ShieldCheck,
    color: "from-cyan-500 to-cyan-600",
  },
  {
    id: 40,
    name: "Car Maintenance & Repairs",
    type: "expense",
    icon: Wrench,
    color: "from-cyan-600 to-cyan-700",
  },
  {
    id: 41,
    name: "Parking & Tolls",
    type: "expense",
    icon: MapPin,
    color: "from-sky-200 to-sky-300",
  },
  {
    id: 42,
    name: "Health Insurance",
    type: "expense",
    icon: Shield,
    color: "from-sky-300 to-sky-400",
  },
  {
    id: 43,
    name: "Medical Expenses",
    type: "expense",
    icon: Heart,
    color: "from-sky-400 to-sky-500",
  },
  {
    id: 44,
    name: "Dental",
    type: "expense",
    icon: Smile,
    color: "from-sky-500 to-sky-600",
  },
  {
    id: 45,
    name: "Pharmacy",
    type: "expense",
    icon: Pill,
    color: "from-sky-600 to-sky-700",
  },
  {
    id: 46,
    name: "Vision Care",
    type: "expense",
    icon: Eye,
    color: "from-blue-200 to-blue-300",
  },
  {
    id: 47,
    name: "Childcare",
    type: "expense",
    icon: Baby,
    color: "from-blue-300 to-blue-400",
  },
  {
    id: 48,
    name: "Education / Tuition",
    type: "expense",
    icon: BookOpen,
    color: "from-blue-400 to-blue-500",
  },
  {
    id: 49,
    name: "Student Loan Payment",
    type: "expense",
    icon: CreditCard,
    color: "from-blue-500 to-blue-600",
  },
  {
    id: 50,
    name: "Life Insurance",
    type: "expense",
    icon: LifeBuoy,
    color: "from-blue-600 to-blue-700",
  },
  {
    id: 51,
    name: "Pet Care",
    type: "expense",
    icon: PawPrint,
    color: "from-indigo-200 to-indigo-300",
  },
  {
    id: 52,
    name: "Clothing & Apparel",
    type: "expense",
    icon: ShoppingBag,
    color: "from-indigo-300 to-indigo-400",
  },
  {
    id: 53,
    name: "Personal Care",
    type: "expense",
    icon: User,
    color: "from-indigo-400 to-indigo-500",
  },
  {
    id: 54,
    name: "Subscriptions & Memberships",
    type: "expense",
    icon: Repeat,
    color: "from-indigo-500 to-indigo-600",
  },
  {
    id: 55,
    name: "Entertainment",
    type: "expense",
    icon: Music,
    color: "from-indigo-600 to-indigo-700",
  },
  {
    id: 56,
    name: "Travel & Vacation",
    type: "expense",
    icon: Plane,
    color: "from-violet-200 to-violet-300",
  },
  {
    id: 57,
    name: "Gifts & Donations",
    type: "expense",
    icon: Gift,
    color: "from-violet-300 to-violet-400",
  },
  {
    id: 58,
    name: "Taxes - Income",
    type: "expense",
    icon: FileText,
    color: "from-violet-400 to-violet-500",
  },
  {
    id: 59,
    name: "Taxes - Other",
    type: "expense",
    icon: FileText,
    color: "from-violet-500 to-violet-600",
  },
  {
    id: 60,
    name: "Banking & Fees",
    type: "expense",
    icon: Banknote,
    color: "from-violet-600 to-violet-700",
  },
  {
    id: 61,
    name: "Business Expenses",
    type: "expense",
    icon: Briefcase,
    color: "from-purple-200 to-purple-300",
  },
  {
    id: 62,
    name: "Office Supplies",
    type: "expense",
    icon: FileText,
    color: "from-purple-300 to-purple-400",
  },
  {
    id: 63,
    name: "Software & Apps",
    type: "expense",
    icon: Cpu,
    color: "from-purple-400 to-purple-500",
  },
  {
    id: 64,
    name: "Investments - Contributions",
    type: "expense",
    icon: Wallet,
    color: "from-purple-500 to-purple-600",
  },
  {
    id: 65,
    name: "Miscellaneous",
    type: "expense",
    icon: MoreHorizontal,
    color: "from-purple-600 to-purple-700",
  },
] as const;

export type TransactionCategory =
  (typeof TransactionCategories)[number]["name"];
